---
- hosts: all
  become: yes
  tasks:

    - name: Add nvtop PPA
      ansible.builtin.apt_repository:
        repo: 'ppa:flexiondotorg/nvtop'

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Download AMDGPU-PRO .deb file
      get_url:
        url: "https://repo.radeon.com/amdgpu-install/23.40.2/ubuntu/jammy/amdgpu-install_6.0.60002-1_all.deb"
        dest: "/tmp/amdgpu-install_6.0.60002-1_all.deb"
      when: not ansible_facts['file_exists']|default(false)

    - name: Install AMDGPU-PRO .deb package
      apt:
        deb: "/tmp/amdgpu-install_6.0.60002-1_all.deb"

    - name: Run amdgpu-install with specific usecase
      command:
        cmd: amdgpu-install --accept-eula --usecase=workstation,rocm

    - name: Add current user to render and video groups
      user:
        name: "mscs"
        groups: render,video
        append: yes

    # - name: Run update-pciids command
    #   command:
    #     cmd: update-pciids


        
    - name: Install nvtop
      apt:
        name: nvtop
        state: present
    
    - name: Install build-essentials
      apt:
        name: build-essential
        state: present
    
    - name: Install build-essentials
      apt:
        name: git
        state: present

    - name: Install tmux
      apt:
        name: tmux
        state: present

    - name: Install btop
      apt:
        name: btop
        state: present

    - name: Install neofetch
      apt:
        name: neofetch
        state: present

    - name: Python3 venv dependency
      apt:
        name: python3.10-venv
        state: present

    - name: Rocm libraries
      apt:
        name: rocmlibs
        state: present

    # - name: tensorflow dependecy
    #   apt:
    #     name: libhsa-runtime64-1
    #     state: present
    # - name: Reboot the system
    #   reboot: